<a href="https://colab.research.google.com/github/ahmedaliqureshi/DL-ML-with-pytorch/blob/main/Basics_pt_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#why:- we need a deep learning to framework to make our model or to perform
#basic operations
#where:- at start
#what:-using import keyword to import library
import torch
#why:-pandas are used for analysing the data
#where:- at sstart
#what: using import keyword to import a library
import pandas as pd
#why:-we need to compute the numbers which are present in the program
#where:- at start
#what:- using import keyword to import a library
import numpy as np
#why;-we need to visulaise the output and the inner working of the model
#where:-at start
#what;- usin the import keyword to import libary
import matplotlib.pyplot as plt
#why:- don't know which verison of torch we are using
#where:- at start
#what;-simple printing the output
print(torch.__version__)

2.10.0+cu128


# creating range of tensors and tensors like

In [2]:
#why:- sometimes we need a single dimension tensor for small work,
#just to have a single dimension of tensor
#where:- this cell
#what:- using arange to create a single dimension of tesnor

one_to_ten = torch.arange(start=1,end=11,step=1)
#where:- start is intial number, end is the last but it takes second last (n-1)
#steps are basically interval between the numbers
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#why:- sometimes we need to change the value of the 1D tesnor, to do that
#we use tensor like so it can take the previous value and replace it what we
#give
#wehre:-in this cell
#what:- using like to replace value of previous 1D tensor

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor attribute

Tensordatatype is one of the 3 main errors we commonly incounter in
pytorch and deeplearning

The 3 of them are:-

1. tensor not right on datatype, to get datatype tensor.dtype
2. tensor not right on device, to get device tensor.device
3. tenosr not right on shape, to get shape tensor.shape

In [4]:
#float 32 tesnor

float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=None, #what datatype of tensor it is (eg;-float32)
                              device=None, #what device is you'r tensor running
                              requires_grad=False) #whether or not to track gradient with this or not
float_32_tensor

#note:- bydefault the datatype of tensor are float

tensor([3., 6., 9.])

In [5]:
float_32_tensor.dtype

torch.float32

In [6]:
#we can also convert the 32 bit to 16 and vise versa

#1st delcare the variable name, the store the float 32 value,
#2nd use type keyword and use torch method float16

# Define float_32_tensor if it's not already defined (e.g., if previous cells weren't run)
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)

float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [7]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [8]:
float_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [9]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [10]:
#to find out the details about the tensor we can use the following
some_tensor = torch.rand(3,4)
some_tensor

print(some_tensor)
print(f"datatype fo tensor:{some_tensor.dtype}") #show the type of data of tensor
print(f"shape of tensor;{some_tensor.shape}") #show the rows and coloumn of tensor
print(f"device tensor is on:{some_tensor.device}") #show on which device is
#running on,note i did change the runtime, yet it shows the cpu

tensor([[0.7756, 0.9423, 0.0612, 0.5991],
        [0.8389, 0.2121, 0.5250, 0.1440],
        [0.2966, 0.2700, 0.4085, 0.0647]])
datatype fo tensor:torch.float32
shape of tensor;torch.Size([3, 4])
device tensor is on:cpu


#Multiplication of tensors

##Tensors operations include:-

## Addition
## Substraction
## Element Multiplication
## Division
## Matrix multiplication

#Two main rules for multiplying the matrics multipication

##1)

In [11]:
#1) To add tensor

#why:- creating a varible and storing a tenosr in it
#where:- in this cell
#what:- using the addition sign (+) of the tensor

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [12]:
#2) To substract tensor

#why:- creating a variable and storing a tensor in in
#where:-in this cell
#what:-using the the substraction sign (-) of tensor

tensor = torch.tensor([1,2,3])
tensor-10

tensor([-9, -8, -7])

In [13]:
#3) To element wise multiply tensor

#why:- creating a variable and storing a tensor in it
#where:-in this cell
#what:-using the multipication sign (*) of tensor

tensor=torch.tensor([1,2,3])
tensor*10

tensor([10, 20, 30])

In [14]:
#4) To divide tensor

#why:- creating a variable and storing a tensor in it
#where:-in this cell
#what:- using the division sign (/) of tensor

tensor=torch.tensor([1,2,3])
tensor/1

tensor([1., 2., 3.])

In [15]:
#5) TO matirx multipication

#why;- to multiply an element to a matrix
#where:-in this cell
#what:-using matmul function of tensor

tensor=torch.tensor([1,2,3])
torch.matmul(tensor,tensor)

tensor(14)

#Rules of matrix multipication

##1) The inner dimensions must match

##eg:- (3,2) and (3,2) cannot be multiplied as they don't have same inner dimensions (i.e dot product requires them to have same number of rows and column to have sucessful multimplication)

##(3,2) @ (3,2) will not work
##(2,3) @ (3,2)  will work

#2) the resulting matrix has the shape of the outer dimesnion

##eg;- (3,2) @ (2,3) will give us (2,2)

In [16]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5700, 0.3309, 0.4378],
        [0.5431, 0.2558, 0.3517],
        [0.0653, 0.3869, 0.4341]])

# Reshaping, stacking, squeezing and unsqueezing tensors

reshaping- reshapes an input tensor ato defined shape

view- returen a view of a input tensor of certain shape but keep the same memory as the origianl.

squeezing- removes all `1` dimensions from tensor.

unsqueezing- add a `1` dimensions to target tensor.

permute- Return a view of input with dimensions permuted in certain way.



In [43]:
#why- to show the squeez and unsqeez operations
#where- in this cell
#what- using abover operation on the following torch for understanding

x=torch.arange(1,13) #1 here represent intial
#element and 10 reprent total number of element

x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [21]:
z=torch.arange(2,12) #here 2 is the intial element, and 12 are the total element
z,z.shape

(tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), torch.Size([10]))

In [38]:
x_reshaped=x.reshape(1,9) #1 represent the number of rows, and
#9 represent total number of columns
x_reshaped,x_reshaped.shape #(note that size is a fucntion)

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [36]:
x_reshaped=x.reshape(9,1) #9 represent the number of rows, and
#1 represent total number of columns
x_reshaped,x_reshaped.shape #(note that size is a fucntion)

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [46]:
# stack tensor on top fo each other

x_stacked = torch.stack ([x,x,x,x,x],dim=1)
x_stacked

tensor([[ 1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9],
        [10, 10, 10, 10, 10],
        [11, 11, 11, 11, 11],
        [12, 12, 12, 12, 12]])

In [ ]:
#torch.squeez will remove all the single dimensions from the targeted tensors

x=