<a href="https://colab.research.google.com/github/ahmedaliqureshi/DL-ML-with-pytorch/blob/main/Basics_pt_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Make sure to import the libraries that are required**

In [21]:
#why:- we need a deep learning to framework to make our model or to perform
#basic operations
#where:- at start
#what:-using import keyword to import library
import torch
#why:-pandas are used for analysing the data
#where:- at sstart
#what: using import keyword to import a library
import pandas as pd
#why:-we need to compute the numbers which are present in the program
#where:- at start
#what:- using import keyword to import a library
import numpy as np
#why;-we need to visulaise the output and the inner working of the model
#where:-at start
#what;- usin the import keyword to import libary
import matplotlib.pyplot as plt
#why:- don't know which verison of torch we are using
#where:- at start
#what;-simple printing the output
print(torch.__version__)

2.10.0+cpu


 ### **Introduction of tensor datatype:-**

 # 1.types of tensor

 # 1.1 scalar

 # 1.2 vector

 # 1.3 matrix

 # 1.4 tensor


In [22]:
 # 1.1 scalar:-

 #why;- scalar is a variable here, where we are passing a value in tensor
 #where:-in this cell
 #what:- scalar is a variable where it is holding a torch.tensor work,then later
 #on calling it

 #note:- scalar are data type which are null dimension

scalar = torch.tensor(7)

scalar

tensor(7)

#And if we want to look at the dimension of datatype,
#use ndim (number of dimensions)

In [23]:
#why:- scalare store the value of the torch.tensor
#where:- in above cell
#what;- to see how many dimensions does the type of number is having we are uing
# ndim

scalar.ndim

0

In [24]:
#1.2 vector:-

#why:- vector is a varibale here,, where we are passing a 1D value in tensor
#where:-in this cell
#what:- vector is a variable where it is holding a torch.tensor work, then later
#on calling it

#note:- vector are data type whcih are 1 dimension

vector = torch.tensor([2,3])

vector


tensor([2, 3])

In [25]:
vector.ndim

1

In [26]:
#1.3 matrix:-

#why:- matrix is the varibale here, where we are passing a 2D value in tensor
#where:- in this cell
#what;- matrix is a vraible where it is holding a torch.tensor work, then later
#on callin it

#note;- matrix are data type which are 2 dimension

matrix = torch.tensor([[2,3],[2,2]])

matrix

tensor([[2, 3],
        [2, 2]])

In [27]:
matrix.ndim

2

In [28]:
#1.4 tesnor;-

#why:-matrix has limitation on stopping at 2D, to push pass it, we need to use
#3D
#where:- in this cell
#what:- tensor is a varaible where it is holding a torch.tensor work, then later
#on calling it

#note:- tensor are data type with 3 dimension

tensor = torch.tensor([[[1,1,1],
                       [2,2,2],
                       [3,3,3]]])

tensor

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

In [29]:
tensor.ndim

3

In [30]:
tensor.shape

torch.Size([1, 3, 3])

In size [1,3,3]

1 over here means the number of matrix present in this tensor

3 over here means the number of vectors present in the matrix

3 over here means the number of

In [31]:
tensor = torch.tensor([[[1,1,1],
                       [2,2,2],
                       [3,3,3]],

                       [[11,12,13],
                        [21,22,23],
                        [31,32,33]],

                       [[1,1,1],
                        [1,1,1],
                        [1,1,1]]
                       ])

print(f"Tensor shape: {tensor.shape}")

Tensor shape: torch.Size([3, 3, 3])


### Random tensors

It tensors are improtant because the way many neural netwroks learn is that they start with tensors full of random numbers and then adjust those random numbers and then adjust those random numbers
to better represent the data.

start with random numbers-> look at data-> update random numbers->
look at data-> update random numbers



In [32]:
#Random tensor

random_tensor= torch.rand(10,10,10)
random_tensor

tensor([[[8.4211e-01, 8.4895e-01, 9.6969e-01, 4.2612e-01, 4.2240e-01,
          3.6379e-01, 4.0283e-01, 6.3468e-01, 6.2591e-01, 4.6362e-02],
         [6.8520e-01, 3.1350e-02, 9.7811e-01, 8.2980e-01, 9.3656e-01,
          7.8256e-01, 9.3201e-01, 4.1087e-01, 8.3284e-01, 4.2846e-01],
         [8.2262e-01, 8.7482e-01, 7.4573e-01, 5.6655e-01, 1.6469e-02,
          2.1888e-01, 9.6965e-01, 8.2059e-01, 5.2714e-01, 7.9246e-01],
         [5.0393e-01, 1.9700e-01, 6.6713e-01, 4.8825e-01, 9.4114e-01,
          9.4352e-01, 7.5560e-02, 1.4746e-01, 6.3210e-01, 2.2860e-01],
         [5.3540e-01, 4.4671e-01, 8.0359e-01, 8.0978e-01, 2.0077e-01,
          9.1857e-01, 6.2629e-01, 9.5045e-01, 4.7192e-01, 8.7422e-01],
         [9.7118e-01, 6.9322e-01, 7.9579e-02, 5.1564e-01, 3.9606e-01,
          5.8850e-01, 2.8052e-01, 7.7517e-01, 9.9057e-01, 8.7978e-01],
         [7.4630e-01, 7.5199e-01, 7.9095e-01, 4.0912e-01, 1.1625e-01,
          1.8690e-02, 8.6340e-01, 9.1916e-01, 3.2572e-01, 6.8226e-01],
         [2.8

In [33]:
#creating a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(244,244,3)) #(height,width,RGB color)
random_image_size_tensor.shape
random_image_size_tensor.ndim


3

# Zeros and ones tenosr

In [34]:
#why:- to see the one and zero only tensor
#where:- in this cell
#what- using variable like of "one" and "zero" to store and call the tensor


zero = torch.zeros(size=(3,4)) #torch.value present in tensor then size of tensor
#(number of rows, number o
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
one = torch.ones(size=(4,5))

one

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])